manifest:
  defaults:
    revision: 904c9aec8822d79149d42c8a9a77e8828eb08f5a
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
